"""empty message

Revision ID: 44ff9c7e95cc
Revises: f3e335cc74ff
Create Date: 2024-01-25 17:28:42.374194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ff9c7e95cc'
down_revision: Union[str, None] = 'f3e335cc74ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = 'f3e335cc74ff'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('floor', sa.Integer(), nullable=False), schema='homedigger')
    op.drop_constraint('advertisements_title_link_price_parking_rooms_size_rent_off_key', 'advertisements', schema='homedigger', type_='unique')
    op.create_unique_constraint(None, 'advertisements', ['title', 'link', 'price', 'parking', 'rooms', 'size', 'floor', 'rent_office_id'], schema='homedigger')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'advertisements', schema='homedigger', type_='unique')
    op.create_unique_constraint('advertisements_title_link_price_parking_rooms_size_rent_off_key', 'advertisements', ['title', 'link', 'price', 'parking', 'rooms', 'size', 'rent_office_id'], schema='homedigger')
    op.drop_column('advertisements', 'floor', schema='homedigger')
    # ### end Alembic commands ###
